AWSTemplateFormatVersion: "2010-09-09"
Description: Specifies the university_ranking tables in the Glue data catalog

Parameters:
  GlueDatabaseNameParameter:
    Type: String
    Description: Enter the Glue database name
  GlueTableLocationParameter:
    Type: String
    Description: Enter the S3 path to the table

Resources:

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref GlueDatabaseNameParameter

  UniversityRankingCSVTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabaseNameParameter
      TableInput:
        Name: university_ranking_csv
        Description: "University Ranking CSV Table"
        TableType: EXTERNAL_TABLE
        Parameters:
          skip.header.line.count: "1"
        StorageDescriptor:
          Columns:
            - Name: university
              Type: string
            - Name: year
              Type: string
            - Name: rank_display
              Type: string
            - Name: score
              Type: string
            - Name: link
              Type: string
            - Name: country
              Type: string
            - Name: city
              Type: string
            - Name: region
              Type: string
            - Name: logo
              Type: string
            - Name: type
              Type: string
            - Name: research_output
              Type: string
            - Name: student_faculty_ratio
              Type: string
            - Name: international_students
              Type: string
            - Name: size
              Type: string
            - Name: faculty_count
              Type: string
          Location: !Ref GlueTableLocationParameter
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
            Parameters:
              separatorChar: ","
              escapeChar: "\\"
              quoteChar: "\""